name: Release

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm64]
        exclude:
          # windows/arm64 seems useless
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v2

      - name: Set APP_VERSION env
        run: echo ::set-env name=APP_VERSION::$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev )
      - name: Set BUILD_TIME env
        run: echo ::set-env name=BUILD_TIME::$(date)
      - name: Set BUILD_USER env
        run: echo ::set-env name=BUILD_USER::$(echo ${GITHUB_ACTOR}@${HOSTNAME})
      - name: Environment Printer
        uses: managedkaos/print-env@v1.0

      - uses: wangyoucao577/go-release-action@v1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          extra_files: LICENSE README.md config.yml
          pre_command: go get -v ./...
          build_flags: -v
          ldflags: -X "main.Version=${{ env.APP_VERSION }}" -X "main.BuildDate=${{ env.BUILD_TIME }}" -X "main.Branch=${{ github.ref }}" -X "main.Revision=${{ github.SHA }}" -X "main.BuildUser=${{ env.BUILD_USER }}"
